#!/usr/bin/env bash
#  Bash script that displays the content of the file /etc/passwd.

#	Your script should only display:

#	username
#	user id
#	Home directory path for the user

while IFS=: read -r username password uid gid gecos home_directory shell; do
	 echo "$username:$uid:$home_directory"

done < /etc/passwd	
