#!/usr/bin/env bash
#  Bash script that groups visitors by IP and HTTP status code, and displays this data.

awk '{count[$1, $9]++ }
END {
	for (key in count) {
       		split(key, arr, SUBSEP) 
		print count[key], arr[1], arr[2] 
	} 
}' apache-access.log | sort -k1,1 -n -r 
